#creating build pipeline for dotnet app
stages:
  - stage: Continousintegration
    displayName: Continousintegration
    jobs:
    - job: dotnetbuild
      displayName: dotnetbuildjob
      steps:
      - script: dotnet restore
        displayName: restore
      - script: dotnet build
        displayName: dotnet build
      - script: dotnet test
        displayName: test
      - script: dotnet publish
        displayName: publish artifact
      




