#creating build pipeline for dotnet app
stages:
  - stage: continous-integration
    displayName: Continous-integration
    jobs:
    - job: dotnetbuild
      displayName: dotnet-build-job
      steps:
      - script: dotnet restore
        displayName: restore
      - script: dotnet build
        displayName: dotnet build
      - script: dotnet test
        displayName: test
      - script: dotnet publish
        displayName: dotnet-publish 
      










  - stage: continous-deployment